### ISSUE TITLE
Raspien Stretch

### ISSUE THREAD

**Issue by AnonSchlingel** [sebastianzillessen/WiFi-AP-Raspberry-Pi-3#1]
Hi, first of all: than you for this script.
Sadly it wont work. I assume, that it has to do with Raspien Stretch.
So Could you please update your script?

**Comment by sebastianzillessen** [comment]
Hi Anon, 
Unfortunately, I did not understand your question. What do you think is the problem with the script and what kind of error messages are you seeing? 

Please have a look at the following post on how to write good Github issues: https://medium.com/nycplanninglabs/writing-a-proper-github-issue-97427d62a20f

Thanks for providing a better error description and as well a proactive solution idea. 

Best,
Sebastian

**Comment by sebastianzillessen** [comment]
Closing because of missing issue description.
